---
apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: spring-petclinic
spec:
  title: Spring Pet Clinic
  icon: https://spring-petclinic.github.io/images/logo-spring.png
  statusInformers:
    - deployment/spring-petclinic
  ports:
    - serviceName: "spring-petclinic"
      servicePort: 80
      localPort: 8080
      applicationUrl: "http://spring-petclinic"
