---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: spring-petclinic
  annotations:
    ext.packaging.carvel.dev/fetch-0-secret-name: replicated-registry
spec:
  serviceAccountName: kotsadm
  packageRef:
    refName: spring-petclinic.spring.io
    versionSelection:
      constraints: 1.0.0
  values:
  - secretRef:
      name: spring-petclinic-values
---
apiVersion: v1
kind: Secret
metadata:
  name: spring-petclinic-values
stringData:
  values.yaml: |
    ---
    svc_port: repl{{ ConfigOption "service_port" | ParseInt }}
    app_port: repl{{ ConfigOption "app_port" | ParseInt }}
    namespace: repl{{ Namespace }}
