---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: spring-petclinic
spec:
  serviceAccountName: kotsadm
  fetch:
  - imgpkgBundle:
      image: registry.replicated.com/spring-pet-clinic-stinkbug/bundle@sha256:9fe8559d8b34e4750013eeb5b43c9ffaded2a53268d3b36b81ccd994f9acbce3
      secretRef: 
        name: replicated-registry

  template:
  - ytt:
      paths:
      - config/
      inline:
        paths:
          values.yaml: |
            #@data/values
            ---
            svc_port: repl{{ ConfigOption "service_port" | ParseInt }}
            app_port: repl{{ ConfigOption "app_port" | ParseInt }}
            namespace: repl{{ Namespace }}
  - kbld:
      paths:
      - '-'
      - .imgpkg/images.yml

  deploy:
    - kapp: {}
