---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: spring-petclinic
spec:
  serviceAccountName: kotsadm
  fetch:
  - imgpkgBundle:
      image: registry.shortrib.dev/library/spring-petclinic-replicated:latest

  template:
  - ytt:
      paths:
      - config/
      inline:
        paths:
          values.yaml: |
            #@data/values
            ---
            svc_port: repl{{ ConfigOption "service_port" | ParseInt }}
            app_port: repl{{ ConfigOption "app_port" | ParseInt }}
            namespace: repl{{ Namespace }}
  - kbld:
      paths:
      - '-'
      - .imgpkg/images.yml

  deploy:
    - kapp: {}
