---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: registry.replicated.com/spring-pet-clinic-stinkbug/petclinic
    kbld.carvel.dev/origins: |
      - resolved:
          tag: latest
          url: registry.replicated.com/spring-pet-clinic-stinkbug/petclinic
      - preresolved:
          url: registry.replicated.com/spring-pet-clinic-stinkbug/petclinic@sha256:6a5c7ba0f125f61f73d89e308b20a7f792f0890578b7813366ffc1fa06dbbc82
  image: registry.replicated.com/spring-pet-clinic-stinkbug/petclinic@sha256:6a5c7ba0f125f61f73d89e308b20a7f792f0890578b7813366ffc1fa06dbbc82
kind: ImagesLock
